services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  producer:
    build: ./producer
    ports:
      - "8001:8001"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
        redis:
          condition: service_healthy
    networks: 
      - backend

  consumer:
    build: ./consumer
    ports:
     - "8002:8002"
    environment:
      MONGO_URI: "mongodb://mongodb:27017"

      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
        redis:
          condition: service_healthy
        mongodb:
          condition: service_healthy
    networks: 
      - backend

networks:
  backend:
    driver: bridge